#adapted from example in docker documentation
version: '3'

services:
  web:
    restart: always
    build: .
    depends_on:
       - redis
    volumes:
       - .:/code
    links:
       - redis:redis
    expose:
       - 8000
    user: "1001:1002" #system dependant
    # command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    working_dir: /code/mysite
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application

  redis:
    image: redis
    expose:
      - 6379

  # nginx:
  #   restart: always
  #   build: ./nginx/
  #   depends_on:
  #     - web
  #   ports:
  #     - 80:80
  #   links:
  #     - web:web
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/mysite/myapp/static:/srv/static/
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

